"""initial migration

Revision ID: 2d7459a323f3
Revises: 
Create Date: 2025-10-16 19:54:12.331130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7459a323f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('arrivaldate', sa.Date(), nullable=True),
    sa.Column('departuredate', sa.Date(), nullable=False),
    sa.Column('foodBudget', sa.Integer(), nullable=False),
    sa.Column('lodgingBudget', sa.Integer(), nullable=False),
    sa.Column('transportationBudget', sa.Integer(), nullable=False),
    sa.Column('activityBudget', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_preferences')
    # ### end Alembic commands ###
