"""added weather column to ItineraryPreferences

Revision ID: 3eb15c827695
Revises: 953a71c86d7c
Create Date: 2025-11-24 11:43:27.965063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb15c827695'
down_revision = '953a71c86d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_preferences', schema=None) as batch_op:
        batch_op.drop_column('weather')

    # ### end Alembic commands ###
