"""initial

Revision ID: 953a71c86d7c
Revises: 
Create Date: 2025-11-24 11:41:39.258174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953a71c86d7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numberOfTravelers', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('arrivaldate', sa.Date(), nullable=True),
    sa.Column('departuredate', sa.Date(), nullable=False),
    sa.Column('foodBudget', sa.Integer(), nullable=False),
    sa.Column('lodgingBudget', sa.Integer(), nullable=False),
    sa.Column('transportationBudget', sa.Integer(), nullable=False),
    sa.Column('activityBudget', sa.Integer(), nullable=False),
    sa.Column('tripDuration', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferences_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('google_places', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preferences_id'], ['itinerary_preferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary')
    op.drop_table('itinerary_preferences')
    # ### end Alembic commands ###
