"""Initial migration.

Revision ID: b040cdb4e4ef
Revises: 
Create Date: 2025-09-24 11:47:31.636553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b040cdb4e4ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transportation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_preferences', schema=None) as batch_op:
        batch_op.drop_column('transportation')

    # ### end Alembic commands ###
