"""added tripDuration

Revision ID: c4a7394aef70
Revises: 2d7459a323f3
Create Date: 2025-10-16 20:10:07.399879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a7394aef70'
down_revision = '2d7459a323f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tripDuration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_preferences', schema=None) as batch_op:
        batch_op.drop_column('tripDuration')

    # ### end Alembic commands ###
