name: Notify Discord

on:
    issues:
        types: [opened, reopened, closed, assigned, edited]

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Send notification to Discord
              env: 
                DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                ACTION: ${{ github.event.action }}
                ISSUE_TITLE: ${{ github.event.issue.title }}
                ISSUE_URL: ${{ github.event.issue.html_url }}
                ISSUE_USER: ${{ github.event.issue.user.login }}
                ISSUE_ASSIGNEE: ${{ github.event.assignee.login || github.event.issue.assignee.login || '' }}
              run: |
                TITLE=${ISSUE_TITLE:-"Untitled issue"}
                URL=${ISSUE_URL:-"https://github.com/${{ github.repository }}/issues"}
                USER=${ISSUE_USER:-"someone"}
                ASSIGNEE=${ISSUE_ASSIGNEE:-"someone"}

                # Determine the message based on the action type
                case "$ACTION" in
                    opened)
                    MSG="🚀 New issue opened by **$USER**: [$TITLE]($URL)"
                    ;;
                    assigned)
                    MSG="👥 Issue assigned to **$ASSIGNEE** by **$USER**: [$TITLE]($URL)"
                    ;;
                    closed)
                    MSG="✅ Issue closed by **$USER**: [$TITLE]($URL)"
                    ;;
                    reopened)
                    MSG="🔄 Issue reopened by **$USER**: [$TITLE]($URL)"
                    ;;
                    edited)
                    MSG="📝 Issue updated by **$USER**: [$TITLE]($URL)"
                    ;;
                    *)
                    MSG="ℹ️ Issue event \`$ACTION\` occurred for [$TITLE]($URL)"
                    ;;
                esac

                echo "Sending message: $MSG"

                PAYLOAD=$(jq -n --arg content "$MSG" '{content: $content}')
                curl -s -H "Content-Type: application/json" \
                    -d "$PAYLOAD" \
                    "$DISCORD_WEBHOOK"